default_platform(:ios)

platform :ios do

  # -----------------------
  # BETA → TestFlight
  # -----------------------
  desc "Upload to TestFlight (Beta)"
  lane :beta do

    latest_build = latest_testflight_build_number(
      app_identifier: "com.ahmed.taskflow"
    ) || 0

    increment_build_number(
      build_number: latest_build + 1,
      xcodeproj: "TaskFlow.xcodeproj"
    )

    build_app(
      scheme: "TaskFlow",
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic"
      }
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )

  end


  # -----------------------
  # PRODUCTION (OPTIONAL)
  # -----------------------
  desc "Upload new build to App Store"
  lane :release do

    latest_build = latest_testflight_build_number(
      app_identifier: "com.ahmed.taskflow"
    ) || 0

    increment_build_number(
      build_number: latest_build + 1,
      xcodeproj: "TaskFlow.xcodeproj"
    )

    build_app(
      scheme: "TaskFlow",
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic"
      }
    )

    upload_to_app_store

  end


  # -----------------------
  # PROMOTE EXISTING BUILD
  # -----------------------
  desc "Promote TestFlight build to production"
  lane :promote do

    upload_to_app_store(
      skip_binary_upload: true,
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: true
    )

  end

end