default_platform(:ios)

platform :ios do

  desc "Build and upload to TestFlight"
  lane :beta do

    build_app(
      scheme: "TaskFlow",
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic"
      }
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )

  end

end