default_platform(:ios)

platform :ios do

  # -----------------------
  # BETA → TestFlight
  # -----------------------
  desc "Upload to TestFlight (Beta)"
  lane :beta do

    # 🔐 API KEY
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"]
    )

    # ✅ IMPORTANT: install certificates
    match(
      type: "appstore",
      readonly: true
    )

    # 📈 Get latest build number
    latest_build = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: "com.ahmed.taskflow"
    ) || 0

    # 🔢 Increment build number
    increment_build_number(
      build_number: latest_build + 1,
      xcodeproj: "TaskFlow.xcodeproj"
    )

    # 🛠 Build (with match profiles)
    build_app(
      scheme: "TaskFlow",
      export_method: "app-store"
    )

    # 🚀 Upload
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )

  end


  # -----------------------
  # PRODUCTION
  # -----------------------
  desc "Upload new build to App Store"
  lane :release do

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"]
    )

    # ✅ IMPORTANT
    match(
      type: "appstore",
      readonly: true
    )

    latest_build = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: "com.ahmed.taskflow"
    ) || 0

    increment_build_number(
      build_number: latest_build + 1,
      xcodeproj: "TaskFlow.xcodeproj"
    )

    build_app(
      scheme: "TaskFlow",
      export_method: "app-store"
    )

    upload_to_app_store(
      api_key: api_key
    )

  end


  # -----------------------
  # PROMOTE
  # -----------------------
  desc "Promote TestFlight build to production"
  lane :promote do

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"]
    )

    upload_to_app_store(
      api_key: api_key,
      skip_binary_upload: true,
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: true
    )

  end

end